import "@/styles/globals.css";

import { type Metadata } from "next";

import {
  ClerkProvider,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Trigify Search",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="noto-sans bg-main text-white">
          <header className="flex justify-end items-center p-4 gap-4 h-16 border-b border-[#3F4454]">
            <SignedOut>
              <div className="bg-blue-500 py-3 px-5 rounded-max text-white hover:bg-blue-600">
                <SignUpButton />
              </div>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
